package pe.yarovi.webservice.services.personaws.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-11-28T17:55:02.688-05:00
 * Generated source version: 3.1.16
 * 
 */
@WebService(targetNamespace = "http://webservice.yarovi.pe/services/personaws/ws", name = "personaWS")
@XmlSeeAlso({pe.yarovi.webservice.entity.ws.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PersonaWS {

    @WebMethod(action = "http://webservice.yarovi.pe/services/personaws/ws/buscarDatos")
    @WebResult(name = "buscarResponse", targetNamespace = "http://webservice.yarovi.pe/entity/ws/types", partName = "response")
    public pe.yarovi.webservice.entity.ws.types.BuscarResponse buscarDatos(
        @WebParam(partName = "request", name = "buscarRequest", targetNamespace = "http://webservice.yarovi.pe/entity/ws/types")
        pe.yarovi.webservice.entity.ws.types.BuscarRequest request
    );
}
